import React from 'react';

// ReportDownload — single button that fetches the generated PDF.
// The backend returns a URL (or a relative path) under `report_url`.
export default function ReportDownload({ reportUrl, filename }) {
  if (!reportUrl) {
    return (
      <div className="card empty-state">
        <div className="empty-state-icon">📄</div>
        Run the pipeline to generate a downloadable PDF report.
      </div>
    );
  }

  // The backend may return either an absolute URL or a relative "/reports/..." path.
  // We let the browser resolve it relative to the API base if it's a path.
  const href = reportUrl.startsWith('http')
    ? reportUrl
    : `${process.env.REACT_APP_API_URL || 'http://localhost:5000'}${reportUrl}`;

  return (
    <div className="card" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
      <div>
        <h3 className="card-title" style={{ marginBottom: 4 }}>
          <span className="icon">📄</span> PDF Report Ready
        </h3>
        <div style={{ color: 'var(--muted)', fontSize: 13 }}>
          {filename || 'autoreport.pdf'} — generated by the Report Agent.
        </div>
      </div>
      <a
        className="btn btn-primary"
        href={href}
        target="_blank"
        rel="noreferrer"
        download
      >
        ⬇️ Download PDF Report
      </a>
    </div>
  );
}